### PR TITLE
08  surf+paddle+rwd

### PR DESCRIPTION
**Pull request by jgarcia99**
http://htmlpreview.github.io/?https://github.com/jgarcia99/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

### CODE REVIEW

**Comment by jgarcia99** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/105

**Comment by eklemen** [comment]
:+1:

**Comment by al-the-x** [comment]
Need more commits... And more peer review would help with those bugs. Set a timer with no more than 25 mins, even if all you do on your break is `git status`, `git add`, `git commit`.

**Comment by jgarcia99** [comment]
@al-the-x yea I get in the "code zone" and forget to commit at times.

**Pull request merged**
